### PR TITLE
dag-service 

### PR DESCRIPTION
**Pull request by daviddias**
> Still working this branch, ~~**do not merge yet**~~, ready now
- [x] finish dag service
- [x] tests
- [x] create a cycle test where a go-ipfs marsheled node is cycled to through our code and make sure the original and end result didn't create any mutation
- [x] method descriptions

### CODE REVIEW

**Comment by daviddias** [comment]
@dignifiedquire @richardlitt could you review this PR? Well, actually, the whole module when it comes to API? The parallel on go-ipfs lives on https://github.com/ipfs/go-ipfs/tree/master/merkledag

@vijayee this is ready to merge :) Can I get your :+1: ?

**Comment by RichardLitt** [comment]
Looks fine to me from looking over the code, but I'm not sure about running it.

**Comment by vijayee** [comment]
Looks good to me.

**Comment by daviddias** [comment]
sweet! :+1:  thank you

**Pull request merged**
